version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  api:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/helpdesk
      # Add other envs
  client:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api